// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using System.Configuration;
using Smocktest;

public class IncidentReport 
{
    public IWebDriver driver { get; private set; }
    public IDictionary<String, Object> vars { get; private set; }
    public IJavaScriptExecutor js { get; private set; }
    public IncidentReport()
    {
        vars = new Dictionary<String, Object>();
    }

    private bool IsElementPresent(IWebDriver driver, By by)
    {
        try
        {

            driver.FindElement(by);
            return true;
        }
        catch (NoSuchElementException)
        {
            return false;
        }
    }
    private void SelectDropDown(IWebDriver driver, By by, String selectoption)
    {
        var dropdown = driver.FindElement(by);
        var selectElement = new SelectElement(dropdown);
        selectElement.SelectByValue(selectoption);

    }

    public void CreateIncidentReport(IWebDriver driver, string Env, string IndividualId)
    {
        driver.Manage().Window.Maximize();
        driver.Navigate().GoToUrl("https://" + Env + ".kywaiver.chfsinet.ky.gov");

        if (IsElementPresent(driver, By.Id("details-button")))
        {
            driver.FindElement(By.Id("details-button")).Click();
            driver.FindElement(By.Id("proceed-link")).Click();
        }
        
        if (!IsElementPresent(driver, By.Name("Accept")))
        {
            if (IsElementPresent(driver, By.Id("ContentPlaceHolder1_lbtnBackToRealm")))
            {
                driver.FindElement(By.Id("ContentPlaceHolder1_lbtnBackToRealm")).Click();
            }

            if (IsElementPresent(driver, By.Id("ContentPlaceHolder1_InternalUserWithEmailAddressPlaceHolder")))
            {
                driver.FindElement(By.Id("ContentPlaceHolder1_InternalUserWithEmailAddressPlaceHolder")).Click();
            }
            else
            {
                driver.FindElement(By.Id("InternalUserWithEmailAddress")).Click();
                driver.FindElement(By.Id("InternalUserWithEmailAddress")).Click();
                driver.FindElement(By.ClassName("button")).Click();
            }
            if (Env.ToUpper() != "EXPL")
            {
                driver.FindElement(By.Id("ContentPlaceHolder1_txtUsername")).SendKeys(Env.ToUpper() + ConfigurationManager.AppSettings.Get("PREre_CMAinternel"));
            }
            else
            {
                driver.FindElement(By.Id("ContentPlaceHolder1_txtUsername")).SendKeys(ConfigurationManager.AppSettings.Get("Postre_cmainte"));
            }
            driver.FindElement(By.Id("ContentPlaceHolder1_txtPassword")).SendKeys("Pa$$w0rd.1");
            driver.FindElement(By.Id("ContentPlaceHolder1_SubmitButton")).Click();
        }

        
        driver.FindElement(By.Name("Accept")).Click();
        driver.FindElement(By.Id("primary_nav_menu_5")).Click();
        driver.FindElement(By.Id("IdentifierType")).Click();
        {
            var dropdown = driver.FindElement(By.Id("IdentifierType"));
            dropdown.FindElement(By.XPath("//option[. = 'Individual Id']")).Click();
        }
        driver.FindElement(By.Id("IdentifierType")).Click();
        driver.FindElement(By.Id("IdentifierValue")).Click();
        driver.FindElement(By.Id("IdentifierValue")).SendKeys(IndividualId);
        driver.FindElement(By.Id("btnSearch1")).Click();
        Thread.Sleep(5000);
        driver.FindElement(By.ClassName("openIndividualSummary"), 100).Click();
        Thread.Sleep(5000);
        driver.FindElement(By.CssSelector("li:nth-child(12) > .button-Summary")).Click();
        Thread.Sleep(100);
        driver.FindElement(By.Name("Create New Incident")).Click();
        driver.FindElement(By.Id("ddlAvailableWaiverPrograms")).Click();
        {
            var dropdown = driver.FindElement(By.Id("ddlAvailableWaiverPrograms"));
            dropdown.FindElement(By.XPath("//option[. = 'Supports for Community Living']")).Click();
        }
        driver.FindElement(By.Id("ddlAvailableWaiverPrograms")).Click();
        driver.FindElement(By.Name("Next")).Click();
        {
            var element = driver.FindElement(By.Name("Next"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        Thread.Sleep(100);
        driver.FindElement(By.Id("SelectedReportingProvider")).Click();
        Thread.Sleep(5000);
        driver.FindElement(By.Id("txtProviderName")).Click();
        driver.FindElement(By.Id("txtProviderName")).SendKeys("a");
        driver.FindElement(By.Id("ddlProgramCode")).Click();
        {
            var dropdown = driver.FindElement(By.Id("ddlProgramCode"));
            dropdown.FindElement(By.XPath("//option[. = 'Supports for Community Living']")).Click();
        }
        driver.FindElement(By.Id("ddlProgramCode")).Click();
        driver.FindElement(By.Id("btnSearchProvider")).Click();
        {
            var element = driver.FindElement(By.Id("btnSearchProvider"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        Thread.Sleep(5000);

        driver.FindElement(By.Id("rdl0")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Id("btnSelectProvider")).Click();
        {
            var element = driver.FindElement(By.Id("btnSelectProvider"));
        }
        Thread.Sleep(5000);
        driver.FindElement(By.Id("btnAddWitness")).Click();
        driver.FindElement(By.Id("WitnessFirstName")).Click();
        driver.FindElement(By.Id("WitnessFirstName")).SendKeys("TEST");
        driver.FindElement(By.Id("WitnessLastName")).SendKeys("TESTLASTNAME");
        driver.FindElement(By.Id("WitnessFirstName")).Click();
        driver.FindElement(By.Id("WitnessFirstName")).SendKeys("TESTFIRSTNAME");
        driver.FindElement(By.CssSelector(".ui-datepicker-trigger")).Click();
        driver.FindElement(By.LinkText("1")).Click();
        driver.FindElement(By.CssSelector("#rdbWitnessGender > div:nth-child(1) > .vlabel:nth-child(2)")).Click();
        driver.FindElement(By.Id("AddressLine1")).Click();
        driver.FindElement(By.Id("AddressLine1")).SendKeys("ADDRESSLINE 1");
        driver.FindElement(By.Id("AddressLine2")).Click();
        driver.FindElement(By.Id("AddressLine2")).SendKeys("ADDRESSLINE");
        driver.FindElement(By.Id("City")).Click();
        driver.FindElement(By.Id("City")).SendKeys("CITY");
        {
            var dropdown = driver.FindElement(By.Id("StateCode"));
            dropdown.FindElement(By.XPath("//option[. = 'KENTUCKY']")).Click();
        }
        driver.FindElement(By.Id("ZipCode5")).Click();
        driver.FindElement(By.Id("ZipCode5")).SendKeys("54321");
        driver.FindElement(By.Id("CountyCode")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Id("EnteredAddress")).Click();
        driver.FindElement(By.Id("chooseAndContinueButton")).Click();
        driver.FindElement(By.Id("ZipCode4")).SendKeys("5342");
        driver.FindElement(By.Id("CountyCode")).Click();
        {
            var dropdown = driver.FindElement(By.Id("CountyCode"));
            dropdown.FindElement(By.XPath("//option[. = 'BOYD']")).Click();
        }
        driver.FindElement(By.Id("CountyCode")).Click();
        driver.FindElement(By.Id("WitnessPhone")).Click();
        driver.FindElement(By.Id("WitnessEmailAddress")).Click();
        driver.FindElement(By.Id("WitnessEmailAddress")).SendKeys("TEST@ABC.COM");
        driver.FindElement(By.Id("ddlRelationShiptoWaiverParticipant")).Click();
        {
            var dropdown = driver.FindElement(By.Id("ddlRelationShiptoWaiverParticipant"));
            dropdown.FindElement(By.XPath("//option[. = 'Authorized Representative/Legal Guardian']")).Click();
        }
        driver.FindElement(By.Id("ddlRelationShiptoWaiverParticipant")).Click();
        driver.FindElement(By.Id("btnSave")).Click();
        Thread.Sleep(500);

        if (IsElementPresent(driver, By.Id("chkIsSameasReportingProvider")))
        {
            driver.FindElement(By.Id("chkIsSameasReportingProvider")).Click();
            Thread.Sleep(1000);
        }
        
        
        driver.FindElement(By.Id("rdbwitness[0]")).Click();
        driver.FindElement(By.Id("btnNext")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Id("dpLocationList")).Click();
        {
            var dropdown = driver.FindElement(By.Id("dpLocationList"));
            dropdown.FindElement(By.XPath("//option[. = 'Waiver Participant’s home - Living with relatives']")).Click();
        }
        driver.FindElement(By.Id("dpLocationList")).Click();
        driver.FindElement(By.Id("IncidentAddress_AddressLine1")).Click();
        driver.FindElement(By.Id("IncidentAddress_AddressLine1")).SendKeys("123 LEXINGTON");
        driver.FindElement(By.Id("IncidentAddress_City")).SendKeys("FRANKFORT");
        driver.FindElement(By.Id("IncidentAddress_StateCode")).Click();
        {
            var dropdown = driver.FindElement(By.Id("IncidentAddress_StateCode"));
            dropdown.FindElement(By.XPath("//option[. = 'KENTUCKY']")).Click();
        }
        driver.FindElement(By.Id("IncidentAddress_StateCode")).Click();
        driver.FindElement(By.CssSelector(".table-row:nth-child(5)")).Click();
        driver.FindElement(By.Id("IncidentAddress_ZipCode5")).Click();
        driver.FindElement(By.Id("IncidentAddress_ZipCode5")).SendKeys("54321");
        {
            var element = driver.FindElement(By.Id("IncidentAddress_ZipCode4"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).ClickAndHold().Perform();
            Thread.Sleep(1000);
        }
        {
            var element = driver.FindElement(By.CssSelector(".lb_overlay"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Release().Perform();
            Thread.Sleep(100);
        }
        driver.FindElement(By.CssSelector("body")).Click();
        driver.FindElement(By.Id("EnteredAddress")).Click();
        driver.FindElement(By.Id("chooseAndContinueButton")).Click();
        driver.FindElement(By.Id("IncidentAddress_ZipCode4")).SendKeys("4321");
        driver.FindElement(By.Id("IncidentAddress_CountyCode")).Click();
        {
            var dropdown = driver.FindElement(By.Id("IncidentAddress_CountyCode"));
            dropdown.FindElement(By.XPath("//option[. = 'BOONE']")).Click();
        }
        driver.FindElement(By.Id("IncidentAddress_CountyCode")).Click();
        driver.FindElement(By.Id("txtBeforeIncidentDesc")).Click();
        driver.FindElement(By.Id("txtBeforeIncidentDesc")).SendKeys("test");
        driver.FindElement(By.Id("txtIncidentDesc")).Click();
        driver.FindElement(By.Id("txtIncidentDesc")).SendKeys("test");
        driver.FindElement(By.Id("txtAfterIncidentDesc")).Click();
        driver.FindElement(By.Id("txtAfterIncidentDesc")).SendKeys("test");
        driver.FindElement(By.Id("BtnNext")).Click();
        {
            var element = driver.FindElement(By.Id("BtnNext"));
            Thread.Sleep(1000);
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        driver.FindElement(By.CssSelector(".table-row:nth-child(4) .ui-datepicker-trigger")).Click();
        driver.FindElement(By.LinkText("1")).Click();
        driver.FindElement(By.Id("notificationTime_0")).Click();
        driver.FindElement(By.Id("notificationTime_0")).SendKeys("1211");
        driver.FindElement(By.Id("ddlNotificationPeriod_0")).Click();
        {
            var dropdown = driver.FindElement(By.Id("ddlNotificationPeriod_0"));
            dropdown.FindElement(By.XPath("//option[. = 'AM']")).Click();
        }
        driver.FindElement(By.Id("ddlNotificationPeriod_0")).Click();
        driver.FindElement(By.Id("ddlNotificationZone_0")).Click();
        {
            var dropdown = driver.FindElement(By.Id("ddlNotificationZone_0"));
            dropdown.FindElement(By.XPath("//option[. = 'CT']")).Click();
        }
        driver.FindElement(By.Id("ddlNotificationZone_0")).Click();
        driver.FindElement(By.Id("notificationMethod_0[0]")).Click();
        driver.FindElement(By.CssSelector("#notificationContactDetails_0 > .table-cell:nth-child(3)")).Click();
        driver.FindElement(By.Id("notificationContactName_0")).SendKeys("contact name");
        driver.FindElement(By.Id("btnNext")).Click();
        Thread.Sleep(2000);
        driver.FindElement(By.CssSelector(".table-cell > .ui-datepicker-trigger")).Click();
        Thread.Sleep(2000);
        driver.FindElement(By.LinkText("1")).Click();
        driver.FindElement(By.Id("txtDiscoveryTime")).Click();
        driver.FindElement(By.Id("ddlDiscoveryTimeAmPm")).Click();
        driver.FindElement(By.Id("txtDiscoveryTime")).Click();
        driver.FindElement(By.Id("txtDiscoveryTime")).SendKeys("1211");
        {
            var dropdown = driver.FindElement(By.Id("ddlDiscoveryTimeAmPm"));
            dropdown.FindElement(By.XPath("//option[. = 'AM']")).Click();
        }
        driver.FindElement(By.Id("ddlDiscoveryTimeAmPm")).Click();
        driver.FindElement(By.Id("ddlDiscoveryTimeETCT")).Click();
        {
            var dropdown = driver.FindElement(By.Id("ddlDiscoveryTimeETCT"));
            dropdown.FindElement(By.XPath("//option[. = 'CT']")).Click();
        }
        driver.FindElement(By.Id("ddlDiscoveryTimeETCT")).Click();
        driver.FindElement(By.CssSelector("#rdbIsDateAndTimeApproximated > div:nth-child(1)")).Click();
        driver.FindElement(By.CssSelector("div:nth-child(1) > .vlabel:nth-child(2)")).Click();
        driver.FindElement(By.Id("dplRoleOfIndividualInIncident")).Click();
        {
            var dropdown = driver.FindElement(By.Id("dplRoleOfIndividualInIncident"));
            dropdown.FindElement(By.XPath("//option[. = 'Alleged Victim']")).Click();
        }
        driver.FindElement(By.Id("dplRoleOfIndividualInIncident")).Click();
        driver.FindElement(By.Id("dplLevelOfSuperVision")).Click();
        {
            var dropdown = driver.FindElement(By.Id("dplLevelOfSuperVision"));
            dropdown.FindElement(By.XPath("//option[. = '24 Hour - Allow Staff Sleep Time']")).Click();
        }
        driver.FindElement(By.Id("dplLevelOfSuperVision")).Click();
        driver.FindElement(By.Id("checkboxIncident0")).Click();
        driver.FindElement(By.Id("dtDatetimeoccured0")).Click();
        driver.FindElement(By.CssSelector("tr:nth-child(1) .ui-datepicker-trigger")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.LinkText("1")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.CssSelector(".tabular-data")).Click();
        driver.FindElement(By.Id("txtIncidentOccurredTime0")).Click();
        driver.FindElement(By.Id("txtIncidentOccurredTime0")).SendKeys("1211");
        Thread.Sleep(1000);
        driver.FindElement(By.Id("IncidentOccurredTimeAmPm0")).Click();
        {
            var dropdown = driver.FindElement(By.Id("IncidentOccurredTimeAmPm0"));
            dropdown.FindElement(By.XPath("//option[. = 'AM']")).Click();
        }
        driver.FindElement(By.Id("IncidentOccurredTimeAmPm0")).Click();
        driver.FindElement(By.Id("ddlIncidentOccurredTimeETCT0")).Click();
        Thread.Sleep(1000);
        {
            var dropdown = driver.FindElement(By.Id("ddlIncidentOccurredTimeETCT0"));
            dropdown.FindElement(By.XPath("//option[. = 'CT']")).Click();
        }
        driver.FindElement(By.Id("ddlIncidentOccurredTimeETCT0")).Click();
        driver.FindElement(By.Id("checkboxIncident1")).Click();
        driver.FindElement(By.CssSelector(".altRows:nth-child(2) .ui-datepicker-trigger")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.LinkText("1")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Id("txtIncidentOccurredTime1")).Click();
        driver.FindElement(By.Id("txtIncidentOccurredTime1")).SendKeys("1211");
        Thread.Sleep(1000);
        driver.FindElement(By.Id("IncidentOccurredTimeAmPm1")).Click();
        {
            var dropdown1 = driver.FindElement(By.Id("IncidentOccurredTimeAmPm1"));
            dropdown1.FindElement(By.XPath("//option[. = 'CT']")).Click();
        }
        Thread.Sleep(1000);
        driver.FindElement(By.Id("IncidentOccurredTimeAmPm1")).Click();
        driver.FindElement(By.Id("ddlIncidentOccurredTimeETCT1")).Click();
        {
            var dropdown = driver.FindElement(By.Id("ddlIncidentOccurredTimeETCT1"));
            dropdown.FindElement(By.XPath("//option[. = 'CT']")).Click();
        }
        Thread.Sleep(1000);
        driver.FindElement(By.Id("ddlIncidentOccurredTimeETCT1")).Click();
        driver.FindElement(By.Id("btnNext")).Click();
        {
            var element = driver.FindElement(By.Id("btnNext"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        Thread.Sleep(5000);
        driver.FindElement(By.Id("checkboxBehaviorType0")).Click();
        driver.FindElement(By.Id("txtConfidentiality")).Click();
        driver.FindElement(By.Id("txtConfidentiality")).SendKeys("confidentiality breach type");
        driver.FindElement(By.Id("btnNext")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.CssSelector("#rbtnAllegedActivity > div:nth-child(1) > .vlabel")).Click();
        driver.FindElement(By.CssSelector("#rbtnWasLawEnforced > div:nth-child(1) > .vlabel")).Click();
        driver.FindElement(By.CssSelector("#rbtnWasThereAnArrest > div:nth-child(1) > .vlabel")).Click();
        driver.FindElement(By.CssSelector("#rbtnHomicidalAttempt > div:nth-child(1) > .vlabel")).Click();
        driver.FindElement(By.CssSelector("#rbtnIllegalSubstance > div:nth-child(1) > .vlabel")).Click();
        driver.FindElement(By.Id("btnNext")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Id("DocumentTypeCode")).Click();
        {
            var dropdown = driver.FindElement(By.Id("DocumentTypeCode"));
            dropdown.FindElement(By.XPath("//option[. = 'Coroners Report']")).Click();
        }
        driver.FindElement(By.Id("DocumentTypeCode")).Click();
        IWebElement fileInput = driver.FindElement(By.Id("File"));
        fileInput.SendKeys(ConfigurationManager.AppSettings.Get("filepath"));
        driver.FindElement(By.Name("AttachDocument")).Click();
        Thread.Sleep(4000);
        driver.FindElement(By.Id("btnSubmit")).Click();
        Thread.Sleep(5000);

        RiskMitigationReport riskMitigationReport = new RiskMitigationReport();
        riskMitigationReport.CreateRiskMitigationReport(driver);
    }
}
