// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using System.Configuration;

public class RiskMitigationReport
{
    public IWebDriver driver { get; private set; }
    public IDictionary<String, Object> vars { get; private set; }
    public IJavaScriptExecutor js { get; private set; }
    public RiskMitigationReport()
    {
        vars = new Dictionary<String, Object>();
    }

    public void CreateRiskMitigationReport(IWebDriver driver)
    {
        Thread.Sleep(12000);

        driver.FindElement(By.Id("reportLinkAction1")).Click(); // Manually select the incident Id on the screen and set the next line for execution
        
        driver.FindElement(By.Id("txtComments")).SendKeys("test");
        driver.FindElement(By.Name("Next")).Click();
        driver.FindElement(By.Id("rbtnIsDeadlineNotificationReceived[0]")).Click();
        driver.FindElement(By.Id("rbtnPersonCurrentStatus[0]")).Click();
        driver.FindElement(By.Id("rbtnWhyCriticalIncidentOccured[0]")).Click();
        driver.FindElement(By.CssSelector("#rbtnCouldCriticalIncidentbePrevented > div:nth-child(1) > .vlabel")).Click();
        driver.FindElement(By.CssSelector("#rbtnHowCriticalIncidentPreventedCode .vlabel:nth-child(2)")).Click();
        driver.FindElement(By.CssSelector("#rbtnWasStaffTrainingIdentified > div:nth-child(1) > .vlabel")).Click();
        driver.FindElement(By.CssSelector("#rbtnWhatStaffTrainingIdentifiedCode .vlabel:nth-child(2)")).Click();
        driver.FindElement(By.CssSelector("#rbtnChangesRequiredforPrevention .vlabel:nth-child(2)")).Click();
        driver.FindElement(By.Id("txtnumberoftimesincidenthappened")).Click();
        driver.FindElement(By.Id("txtnumberoftimesincidenthappened")).SendKeys("test");
        driver.FindElement(By.Id("txtactiontakenforsafety")).SendKeys("test");
        driver.FindElement(By.Id("txtstaffrecommendations")).Click();
        driver.FindElement(By.Id("txtstaffrecommendations")).SendKeys("test");
        driver.FindElement(By.Id("txtotherrecommendations")).Click();
        driver.FindElement(By.Id("txtotherrecommendations")).SendKeys("test");
        driver.FindElement(By.Id("txtpolicies")).Click();
        driver.FindElement(By.Id("txtpolicies")).SendKeys("test");
        driver.FindElement(By.Id("txtagencyfindings")).Click();
        driver.FindElement(By.Id("txtagencyfindings")).SendKeys("test");
        driver.FindElement(By.Id("txtadjustmentstopolicies")).Click();
        driver.FindElement(By.Id("txtadjustmentstopolicies")).SendKeys("test");
        driver.FindElement(By.Id("txtresponsibleparticipant")).Click();
        driver.FindElement(By.Id("txtresponsibleparticipant")).SendKeys("test");
        driver.FindElement(By.Id("ProviderActionComments")).Click();
        driver.FindElement(By.Id("ProviderActionComments")).SendKeys("test");
        driver.FindElement(By.Id("btnNext")).Click();
        Thread.Sleep(1000);

        driver.FindElement(By.Id("btnNext")).Click();
        {
            var element = driver.FindElement(By.Id("btnNext"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
            Thread.Sleep(1000);
        }
        driver.FindElement(By.Id("btnNext")).Click();
        Thread.Sleep(1000);

        driver.FindElement(By.CssSelector(".table-row:nth-child(3) > .width-35percent:nth-child(2)")).Click();
        driver.FindElement(By.Id("checkboxBehaviorType0")).Click();
        driver.FindElement(By.Id("txtConfidentiality")).Click();
        driver.FindElement(By.Id("txtConfidentiality")).SendKeys("test");
        driver.FindElement(By.Id("btnNext")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.CssSelector("#rbtnAllegedActivity > div:nth-child(1) > .vlabel")).Click();
        driver.FindElement(By.CssSelector("#rbtnWasLawEnforced > div:nth-child(1) > .vlabel")).Click();
        driver.FindElement(By.CssSelector("#rbtnWasThereAnArrest > div:nth-child(1) > .vlabel")).Click();
        driver.FindElement(By.CssSelector("#rbtnHomicidalAttempt > div:nth-child(1) > .vlabel")).Click();
        driver.FindElement(By.CssSelector("#rbtnIllegalSubstance > div:nth-child(1) > .vlabel")).Click();
        driver.FindElement(By.Id("btnNext")).Click();
        Thread.Sleep(1000);

        driver.FindElement(By.Id("DocumentTypeCode")).Click();
        {
            var dropdown = driver.FindElement(By.Id("DocumentTypeCode"));
            dropdown.FindElement(By.XPath("//option[. = 'Coroners Report']")).Click();
        }
        driver.FindElement(By.Id("DocumentTypeCode")).Click();
        IWebElement fileInput = driver.FindElement(By.Id("File"));
        fileInput.SendKeys(ConfigurationManager.AppSettings.Get("filepath"));
        driver.FindElement(By.Name("AttachDocument")).Click();
        Thread.Sleep(5000);
        driver.FindElement(By.Id("btnSubmit")).Click();
    }
}
